# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0 #v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-executables-have-shebangs
    -   id: detect-aws-credentials
        args: ["--allow-missing-credentials"] # Allow hook to pass when no credentials are detected
    - id: check-ast
    - id: check-builtin-literals
    - id: debug-statements
    - id: requirements-txt-fixer
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.1.9
  hooks:
    - id: ruff #linter
      args: [ --fix ]
    - id: ruff-format #formatter
# - repo: https://github.com/PyCQA/bandit
#   rev: '1.7.5' # Update me!
#   hooks:
#   - id: bandit
#     name: security check for python (bandit)
#     description: 'Bandit is a tool for finding common security issues in Python code'
#     #args: ["-c", "pyproject.toml"]
#     #additional_dependencies: ["bandit[toml]"]

#-   repo: https://github.com/psf/black
#    rev: 23.9.1 #stable
#    hooks:
#    -   id: black
#        language_version: python3

#-   repo: https://github.com/PyCQA/flake8 #https://gitlab.com/pycqa/flake8
#    rev: 6.1.0 #3.7.5
#    hooks:
#    -   id: flake8
#        args: ["--config=.flake8"]
